package com.epam.practice.java9and11;

import java.lang.reflect.InvocationTargetException;
import java.util.Arrays;

/**
 * Difference:
	•  Java 8:
	•  Inner and outer classes are compiled as separate classes.
	•  Private members of the outer class are accessed by the inner class using synthetic bridge methods (compiler-generated).
	•  Reflection cannot access private members of the nest partner directly.
	•  Java 11:
	•  Introduces the concept of a "nest" (a group of classes that are logically part of the same code entity, 
	e.g., an outer class and its inner classes).
	•  Classes in the same nest (nestmates) can access each other's private members directly, without synthetic methods.
	•  Reflection APIs (Class.getNestHost(), Class.getNestMembers(), etc.) are added.
 */
public class SyntheticClassDiff8And11 {

	public static void main(String[] args) {
		 Outer outer = new Outer();
		 Outer.Inner inner = outer.new Inner();
		 inner.printSecret();
		 
		 Class<?> outer1= Outer.class;
		 System.out.println(outer1.getNestHost()); // Outer
		 System.out.println(Arrays.toString(outer1.getNestMembers())); // [Outer, Outer$Inner]

		Class<?>[]  nestMembers = Outer.class.getNestMembers();
		for(Class<?> member : nestMembers) {
			if(member.getSimpleName().equals("Inner")) {
				Outer outer3 = new Outer();
				Object inner3;
				try {
					
					inner3 = member.getDeclaredConstructor(Outer.class).newInstance(outer3);
					   // Invoke printSecret
			        member.getDeclaredMethod("printSecret").invoke(inner);
				} catch (InstantiationException | IllegalAccessException | IllegalArgumentException
						| InvocationTargetException | NoSuchMethodException | SecurityException e) {
					// TODO Auto-generated catch block
					e.printStackTrace();
				}
			}
				
		}

	}

}

/**
 * In Java 8, synthetic methods are generated by the compiler to allow inner classes to access private members of 
 * the outer class. These methods are not visible in the source code but can be seen using reflection or by 
 * decompiling the .class files.

How to see synthetic methods:
	1. Compile your code (Java 8).
	2. Use `javap -p` to inspect the compiled class:
	   javap -p com.epam.dsa.practice.alpha.code.Outer
	   Look for methods marked as synthetic.
	   private synthetic int access$000(com.epam.dsa.practice.alpha.code.Outer);
	   	   
	3. This method is compiler-generated to allow the inner class to access the private field secret of the outer class. 
			In Java 11, this synthetic method will not be present due to nest-based access control.
 */
/** java 11
 * Class<?> outer = Outer.class;
System.out.println(outer.getNestHost()); // Outer
System.out.println(Arrays.toString(outer.getNestMembers())); // [Outer, Outer$Inner]

 */
class Outer {
    private int secret = 42;
    class Inner {
        void printSecret() {
        	// Access via synthetic method
        	
        	// Direct access, no synthetic method
            System.out.println(secret); 
        }
    }
    
    
}


